#!/usr/bin/perl -w

use BR;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "BusRoute",
   ReceiveHandler => \&Receive);
$UNIVERSAL::br = BR->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::br->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::br->Execute();

